# Generated by Django 4.2 on 2023-04-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_referal"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PortfolioItem",
        ),
    ]
