# Generated by Django 4.2 on 2023-04-13 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0005_delete_portfolioitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptocurrency",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cryptocurrency",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cryptocurrencies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cryptocurrency",
            unique_together={("user", "name")},
        ),
        migrations.DeleteModel(
            name="Wallet",
        ),
    ]
