# Generated by Django 4.2 on 2023-04-14 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0006_cryptocurrency_quantity_cryptocurrency_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptocurrency",
            name="id_from_api",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
