# Generated by Django 4.2 on 2023-04-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_cryptocurrency_id_from_api_alter_portfolio_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptocurrency",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
